import React, { useState } from "react";
import {
  MOCK_STUDENTS,
  MOCK_TEACHERS,
  MOCK_TRANSACTIONS,
} from "../../constants";
import {
  TrendingUp,
  Users,
  GraduationCap,
  DollarSign,
  Clock,
  CheckCircle,
  BookOpen,
  Sparkles,
  Bot,
  ArrowUpRight,
} from "lucide-react";
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";

const data = [
  { name: "Jan", revenue: 4000, students: 2400 },
  { name: "Feb", revenue: 3000, students: 1398 },
  { name: "Mar", revenue: 5000, students: 9800 },
  { name: "Apr", revenue: 2780, students: 3908 },
  { name: "May", revenue: 4890, students: 4800 },
  { name: "Jun", revenue: 6390, students: 3800 },
];

const SchoolAdminDashboard = () => {
  const [showAIModal, setShowAIModal] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [aiContent, setAIContent] = useState("");

  const stats = [
    {
      label: "Total Students",
      value: "1,240",
      icon: GraduationCap,
      color: "bg-blue-500",
      trend: "+4% from last month",
    },
    {
      label: "Total Staff",
      value: "84",
      icon: Users,
      color: "bg-purple-500",
      trend: "Stable",
    },
    {
      label: "Monthly Revenue",
      value: "$42,500",
      icon: DollarSign,
      color: "bg-green-500",
      trend: "+12.5% vs May",
    },
    {
      label: "Avg Attendance",
      value: "94.2%",
      icon: TrendingUp,
      color: "bg-orange-500",
      trend: "+1.2% this week",
    },
  ];

  const handleGenerateAIReport = () => {
    setIsGenerating(true);
    setShowAIModal(true);
    setTimeout(() => {
      setAIContent(`**Vidyanta School Health Report**

**Operational Overview:**
- **Enrollment:** Increased by 4% this month. Kindergarten admissions are at 95% capacity.
- **Financial Health:** Revenue is up 12.5% due to early bird fee collections for the next term.
- **Academic Performance:** School-wide average grade has improved from B to B+.
- **Staff Utilization:** Teaching staff are at 88% capacity. 2 new hires recommended for the upcoming Science block.

**AI Action Plan:**
1. Investigate the 5% drop in 9th-grade attendance.
2. Optimize bus route #4 to reduce fuel costs by approximately 8%.
3. Launch "Parent-Teacher Connect" campaign for the upcoming exams.

*Generated by EduNexus AI Core on ${new Date().toLocaleDateString()}*`);
      setIsGenerating(false);
    }, 1500);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-3xl font-bold text-slate-900">
            Executive Overview
          </h2>
          <p className="text-slate-500 font-medium">
            Welcome back, Principal Dsouza.
          </p>
        </div>
        {/* <div className="flex items-center gap-3">
          <button
            onClick={handleGenerateAIReport}
            className="flex items-center gap-2 bg-indigo-600 text-white px-6 py-3 rounded-2xl font-bold hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-200"
          >
            <Sparkles size={18} />
            Generate AI Health Report
          </button>
        </div> */}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {stats.map((stat, idx) => (
          <div
            key={idx}
            className="bg-white p-6 rounded-3xl shadow-sm border border-slate-100 flex flex-col gap-4 hover:shadow-md transition-all group"
          >
            <div className="flex items-center justify-between">
              <div
                className={`${stat.color} p-3 rounded-2xl text-white shadow-lg shadow-slate-100`}
              >
                <stat.icon size={24} />
              </div>
              <div className="flex items-center gap-1 text-[10px] font-bold text-emerald-600 bg-emerald-50 px-2 py-1 rounded-lg">
                <ArrowUpRight size={12} />
                {stat.trend.split(" ")[0]}
              </div>
            </div>
            <div>
              <p className="text-sm text-slate-500 font-semibold mb-1">
                {stat.label}
              </p>
              <h3 className="text-3xl font-extrabold text-slate-900">
                {stat.value}
              </h3>
              <p className="text-[10px] text-slate-400 font-bold uppercase mt-2 tracking-wider">
                {stat.trend}
              </p>
            </div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-white p-8 rounded-[2rem] shadow-sm border border-slate-100">
          <div className="flex items-center justify-between mb-8">
            <h3 className="text-xl font-bold text-slate-900">
              Financial Growth
            </h3>
            <select className="bg-slate-50 text-xs font-bold px-3 py-1.5 rounded-xl border-none">
              <option>Yearly View</option>
            </select>
          </div>
          <div className="h-[300px]">
            <ResponsiveContainer
              width="100%"
              height="100%"
              minWidth={0}
              minHeight={300}
            >
              <AreaChart data={data}>
                <defs>
                  <linearGradient id="colorRevenue" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#6366f1" stopOpacity={0.1} />
                    <stop offset="95%" stopColor="#6366f1" stopOpacity={0} />
                  </linearGradient>
                </defs>
                <CartesianGrid
                  strokeDasharray="3 3"
                  vertical={false}
                  stroke="#f1f5f9"
                />
                <XAxis
                  dataKey="name"
                  axisLine={false}
                  tickLine={false}
                  tick={{ fill: "#94a3b8", fontSize: 12 }}
                  dy={10}
                />
                <YAxis
                  axisLine={false}
                  tickLine={false}
                  tick={{ fill: "#94a3b8", fontSize: 12 }}
                />
                <Tooltip
                  contentStyle={{
                    borderRadius: "16px",
                    border: "none",
                    boxShadow: "0 10px 15px -3px rgb(0 0 0 / 0.1)",
                  }}
                />
                <Area
                  type="monotone"
                  dataKey="revenue"
                  stroke="#6366f1"
                  strokeWidth={3}
                  fillOpacity={1}
                  fill="url(#colorRevenue)"
                />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="bg-white p-8 rounded-[2rem] shadow-sm border border-slate-100">
          <h3 className="text-xl font-bold text-slate-900 mb-6">
            Recent Transactions
          </h3>
          <div className="space-y-4">
            {MOCK_TRANSACTIONS.slice(0, 5).map((tx) => (
              <div
                key={tx.id}
                className="flex items-center justify-between p-4 rounded-2xl hover:bg-slate-50 transition-colors border border-transparent hover:border-slate-100"
              >
                <div className="flex items-center gap-4">
                  <div
                    className={`w-12 h-12 rounded-2xl flex items-center justify-center ${
                      tx.type === "Fee"
                        ? "bg-green-100 text-green-600"
                        : "bg-amber-100 text-amber-600"
                    }`}
                  >
                    {tx.type === "Fee" ? (
                      <CheckCircle size={20} />
                    ) : (
                      <Clock size={20} />
                    )}
                  </div>
                  <div>
                    <p className="font-bold text-slate-900">{tx.studentName}</p>
                    <p className="text-xs text-slate-500 font-medium">
                      {tx.type} • {tx.date}
                    </p>
                  </div>
                </div>
                <p
                  className={`font-bold text-lg ${
                    tx.type === "Fee" ? "text-emerald-600" : "text-slate-900"
                  }`}
                >
                  {tx.type === "Fee" ? "+" : ""}${tx.amount}
                </p>
              </div>
            ))}
          </div>
          <button className="w-full mt-8 py-3 bg-slate-50 text-indigo-600 font-bold rounded-2xl hover:bg-indigo-50 transition-colors">
            Access Full Ledger
          </button>
        </div>
      </div>

      {/* AI Health Modal */}
      {showAIModal && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center z-[100] p-4">
          <div className="bg-white w-full max-w-2xl rounded-[2.5rem] shadow-2xl overflow-hidden border border-slate-100">
            <div className="bg-indigo-600 p-8 text-white relative">
              <div className="relative z-10 flex items-center gap-4">
                <div className="w-12 h-12 bg-white/20 rounded-2xl flex items-center justify-center backdrop-blur-md">
                  <Bot size={28} />
                </div>
                <div>
                  <h3 className="text-2xl font-bold">School Health Report</h3>
                  <p className="text-indigo-100 text-sm">
                    Artificial Intelligence Operations Center
                  </p>
                </div>
              </div>
              <div className="absolute top-0 right-0 w-32 h-32 bg-white/10 rounded-full -translate-y-1/2 translate-x-1/2 blur-2xl"></div>
            </div>

            <div className="p-8">
              {isGenerating ? (
                <div className="py-12 flex flex-col items-center justify-center gap-4">
                  <div className="w-12 h-12 border-4 border-indigo-100 border-t-indigo-600 rounded-full animate-spin"></div>
                  <p className="font-bold text-slate-400 animate-pulse">
                    Computing operational metrics...
                  </p>
                </div>
              ) : (
                <div className="prose prose-slate max-w-none">
                  <div className="whitespace-pre-line text-slate-600 leading-relaxed font-medium">
                    {aiContent}
                  </div>
                </div>
              )}

              <div className="mt-8 pt-6 border-t border-slate-100 flex justify-end">
                <button
                  onClick={() => setShowAIModal(false)}
                  className="px-8 py-3 bg-slate-900 text-white rounded-2xl font-bold hover:bg-slate-800 transition-colors"
                >
                  Confirm Receipt
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default SchoolAdminDashboard;
